routes/front.php
<?php
AdvancedRoute::controller('auth', 'AuthController');
AdvancedRoute::controller('profile', 'ProfileController');
AdvancedRoute::controller('notifications', 'NotificationsController');
AdvancedRoute::controller('roles', 'RolesController');
AdvancedRoute::controller('countries', 'CountriesController');
AdvancedRoute::controller('currencies', 'CurrenciesController');
AdvancedRoute::controller('users', 'UsersController');
AdvancedRoute::controller('posts', 'PostsController');
AdvancedRoute::controller('dashboard', 'DashBoardController');
AdvancedRoute::controller('events', 'EventsController');
AdvancedRoute::controller('groups', 'GroupsController');
AdvancedRoute::controller('programs', 'ProgramsController');
AdvancedRoute::controller('items', 'ItemsController');
AdvancedRoute::controller('contacts', 'ContactsController');
AdvancedRoute::controller('children', 'ChildrenController');
AdvancedRoute::controller('/', 'DashBoardController');

routes/web.php
<?php
/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

/* Route::get('/', function () {
  return view('welcome');
  });
 */
Route::group(['prefix'=>(app()->environment()=='testing')?'en':LaravelLocalization::setLocale(), 'middleware'=>[ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function() {
    AdvancedRoute::controller('auth', 'AuthController');
    Route::group(['middleware'=>['auth']], function() {
        AdvancedRoute::controller('profile', 'ProfileController');
        AdvancedRoute::controller('notifications', 'NotificationsController');
        Route::group(['middleware'=>['isAdmin'], 'prefix'=>'admin'], function() {
            AdvancedRoute::controller('roles', 'Admin\RolesController');
            AdvancedRoute::controller('countries', 'Admin\CountriesController');
            AdvancedRoute::controller('currencies', 'Admin\CurrenciesController');
            AdvancedRoute::controller('users', 'Admin\UsersController');
            AdvancedRoute::controller('items', 'Admin\ItemsController');
            AdvancedRoute::controller('sections', 'Admin\SectionsController');
            AdvancedRoute::controller('vendors', 'Admin\VendorsController');
            AdvancedRoute::controller('logs', 'Admin\LogsController');
            AdvancedRoute::controller('configs', 'Admin\ConfigsController');
            AdvancedRoute::controller('search', 'Admin\SearchController');
            AdvancedRoute::controller('translator', 'Admin\TranslatorController');
            AdvancedRoute::controller('options', 'Admin\OptionsController');
            AdvancedRoute::controller('ajax', 'Admin\AjaxController');
            AdvancedRoute::controller('/', 'Admin\DashBoardController');
        });
    });
    AdvancedRoute::controller('/', 'HomeController');
});


Route::prefix('api')->group(function () {
    require_once __DIR__ . '/api.php';
});

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

class Country extends BaseModel {

    use SoftDeletes,
        \App\Models\Traits\Logger,
        \App\Models\Traits\CreatedBy,
        \Spatie\Translatable\HasTranslations;
    ///////////////////////////// has translation
    public $translatable = ['title'];
    protected $table = "countries";
    protected $guarded = [
        'deleted_at',
        'logged_user'
    ];
    protected $hidden = [
        'deleted_at',
    ];
    public $rules = [
        'iso' => 'required|size:2',
        'title' => 'required',
    ];

    public function getNameAttribute() {
        return @$this->getTranslation('title', lang()) . ' (' . @$this->attributes['iso'] . ')';
    }

    public function getData() {
        return $this;
    }

    public function export($rows, $fileName) {
        if ($rows) {
            foreach ($rows as $row) {
                unset($object);
                $object['id'] = $row->id;
                $object['Short code'] = $row->iso;
                $object['Title'] = @$row->title;
                $object['Created at'] = $row->created_at;
                $labels = array_keys($object);
                $data[] = $object;
            }
            export($data, $labels, $fileName);
        }
    }

}

app/Models/Log.php
<?php

namespace App\Models;

class Log extends BaseModel {

    protected $table = "logs";
    protected $guarded = [
        'deleted_at',
    ];
    protected $hidden = [
        'deleted_at',
        'logged_user'
    ];

    public static function boot() {
        parent::boot();
        static::creating(function ($model) {
            $model->setCreatedAt($model->freshTimestamp());
        });
    }

    public function user() {
        return $this->belongsTo(User::class, 'user_id')->withDefault();
    }

    public function loggable() {
        return $this->morphTo();
    }

    public function scopeAction($q, $action) {
        return $q->where('action', $action);
    }

    public function scopeWasDeleted($q) {
        return $q->action('deleted');
    }

    public function scopeWasUpdated($q) {
        return $q->action('updated');
    }

    public function scopeWasCreated($q) {
        return $q->action('created');
    }

    public function scopeBetween($q, $start, $end) {
        return $q->whereBetween('created_at', [$start, $end]);
    }

    public function scopeEntity($q, $loggableType, $loggableId) {
        return $q->where('loggable_type', $loggableType)
                        ->where('loggable_id', $loggableId);
    }

    public function scopeStateOn($q, $datetime) {
        $query = clone ($q);
        $class = $q->first()->loggable_type;
        $attrs = $q->wasCreated()->first()->after;
        $changes = $query->wasUpdated()
                ->where('created_at', '<=', $datetime)
                ->get();
        foreach ($changes as $change) {
            $attrs = array_merge($attrs, $change->after);
        }
        return new $class($attrs);
    }

    public function getBeforeAttribute($value) {
        return $value ? (array) json_decode($value) : null;
    }

    public function getAfterAttribute($value) {
        return $value ? (array) json_decode($value) : null;
    }

    public function getData() {
        return $this->with(['user'])->when(request('from'), function($q) {
                    $q->where('created_at', '>=', request('from'));
                })->when(request('to'), function($q) {
                    $q->where('created_at', '<', date('Y-m-d', strtotime(request('to') . ' + 1 day')));
                })->latest();
    }

}

app/Http/Controllers/Admin/LogsController.php
<?php

namespace App\Http\Controllers\Admin;

class LogsController extends \App\Http\Controllers\Controller {

    public $model;
    public $module;

    public function __construct(\App\Models\Log $model) {
        $this->module='admin/logs';
        $this->title=trans('app.Logs');
        $this->model=$model;
    }

    public function getIndex() {
        $data['module']=$this->module;
        $data['page_title']=trans('app.List')." ".$this->title;
        $data['rows']=$this->model->getData()->paginate(env('PAGE_LIMIT', 20));
        return view($this->module.'.index', $data);
    }

    public function getView($id) {
        authorize('view-'.$this->module);
        $data['module']=$this->module;
        $data['page_title']=trans('app.View')." ".$this->title;
        $data['breadcrumb']=[$this->title=>$this->module];
        $data['row']=$this->model->findOrFail($id);
        return view($this->module.'.view', $data);
    }

    public function getDelete($id) {
        authorize('delete-'.$this->module);
        $row=$this->model->findOrFail($id);
        $row->delete();
        flash()->success(trans('app.Deleted Successfully'));
        return redirect(lang().'/'.$this->module);
    }
}

resources/views/admin/logs/index.blade.php
@extends('admin.layouts.master')
@section('title')
<h6 class="slim-pagetitle">
    {{ @$page_title }}
</h6>
@endsection
@section('content')
<div class="section-wrapper">
    {!! Form::open(['method' => 'get','files' => true] ) !!} 
    <div class="row mg-t-20 mg-b-20">
        <div class="col-sm-5 mg-t-10 mg-sm-t-0">
            {!! Form::text('from',request('from'),['class'=>'form-control datepicker','placeholder'=>trans('logs.From'),'id'=>'from_date']) !!}
        </div>
        <div class="col-sm-5 mg-t-10 mg-sm-t-0">
            {!! Form::text('to',request('to'),['class'=>'form-control datepicker','placeholder'=>trans('logs.To'),'id'=>'to_date']) !!}
        </div>
        <div class="col-sm-2">
            <input type="submit" class="btn btn-primary bd-0" value="{{ trans('logs.Search') }}">
        </div>
    </div>
    {!! Form::close() !!}
    @if(can('view-'.$module))
    @if (!$rows->isEmpty())
    <div class="table-responsive">
        <table class="table display responsive nowrap">
            <thead>
                <tr>
                    <th class="wd-10p">{{trans('logs.ID')}} </th>
                    <th class="wd-15p">{{trans('logs.Action')}} </th>
                    <th class="wd-15p">{{trans('logs.Module')}} </th>
                    <th class="wd-15p">{{trans('logs.User')}} </th>
                    <th class="wd-15p">{{trans('logs.Created at')}}</th>
                    <th class="wd-15p">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($rows as $row)
                <tr>
                    <td class="center"><a href="{{config('key_modules.'.$row->loggable_type).'/view/'.$row->loggable_id}}">{{$row->id}}</a></td>
                    <td class="center">{{ucfirst($row->action)}}</td>
                    <td class="center">{{ucfirst(config('key_modules.'.$row->loggable_type))}}</td>
                    <td class="center">{{$row->user->name}}</td>
                    <td class="center">{{$row->created_at}}</td>
                    <td class="center">
                        @if(can('view-'.$module))
                        <a class="btn btn-primary btn-xs" href="{{$module}}/view/{{$row->id}}" title="{{trans('logs.View')}}">
                            <i class="fa fa-eye"></i>
                        </a>
                        @endif

                        @if(can('delete-'.$module))
                        <a class="btn btn-danger btn-xs" href="{{$module}}/delete/{{$row->id}}" title="{{trans('logs.Delete')}}" data-confirm="{{trans('logs.Are you sure you want to delete this item')}}?">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div>
        {!! $rows->appends(['from'=>request('from'),'to'=>request('to')])->render() !!}
    </div>
    @else
    {{trans("logs.There is no results")}}
    @endif
    @endif
</div>
@endsection

resources/views/admin/logs/view.blade.php
@extends('admin.layouts.master')
@section('title')
<h6 class="slim-pagetitle">
    {{ @$page_title }}
</h6>
@endsection
@section('content')
<div class="section-wrapper">
    <div class="table-responsive">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered pull-left">
            <tr>
                <td width="25%" class="align-left">{{trans('logs.Action')}}</td>
                <td width="75%" class="align-left">{{ucfirst($row->action)}}</td>
            </tr>
            <tr>
                <td width="25%" class="align-left">{{trans('logs.Module')}}</td>
                <td width="75%" class="align-left">{{ucfirst(config('key_modules.'.$row->loggable_type))}}</td>
            </tr>
            <tr>
                <td width="25%" class="align-left">{{trans('logs.User')}}</td>
                <td width="75%" class="align-left">{{$row->user->name}}</td>
            </tr>
            <tr>
                <td width="25%" class="align-left">{{trans('logs.Created at')}}</td>
                <td width="75%" class="align-left">{{$row->created_at}}</td>
            </tr>
        </table>
    </div>
    @if($row->after)
    <div class="table-responsive">
        <table class="table display responsive nowrap">
            <thead>
                <tr>
                    <th class="wd-15p">{{trans('logs.Field')}} </th>
                    <th class="wd-15p">{{trans('logs.After')}} </th>
                    <th class="wd-15p">{{trans('logs.Before')}} </th>
                    <th class="wd-15p">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach($row->after as $key=>$value)
                <tr>
                    <td class="center"><b>{{ucfirst($key)}}</b></td>
                    <td class="center">{{@$row->after[$key]}}</td>
                    <td class="center">{{@$row->before[$key]}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

</div>
@endsection